[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/db",
    "crates/chain"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
domain = { path = "crates/domain" }
chain = { path = "crates/chain" }

sqlx = { version = "0.8", default-features = false, features = [
    "postgres",
    "runtime-tokio",
    "uuid",
    "macros",
] }

alloy = { version = "2", default-features = false, features = [
    "contract",
    "provider-http",
    "rpc-types",
    "sol-types",
] }

serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
thiserror = "2"
dotenvy = "0.15"
toml = "0.8"