[workspace]
resolver = "2"
members = [
    "crates/domain",
    "crates/db"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
domain = { path = "crates/domain" }

sqlx = { version = "0.8", default-features = false, features = [
    "postgres",
    "runtime-tokio",
    "uuid",
    "macros",
] }

tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
thiserror = "2"
dotenvy = "0.15"
